# version: '3.8'

# services:
#   app:
#     image: prom-app:1.0
#     build: 
#       context: .
#     ports:
#       - "8001:8001"
#     depends_on:
#       - db

#   db:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: obsrv_userr
#       POSTGRES_PASSWORD: obsrv123
#       POSTGRES_DB: obsrv
#     # ports:
#     #   - "5435:5432"
#     volumes:
#     - ./query.sql:/docker-entrypoint-initdb.d/query.sql
#       # - pgdata:/var/lib/postgresql/data

#   # prometheus:
#   #   image: prom/prometheus
#   #   ports:
#   #     - "9090:9090"
#   #   volumes:
#   #     # - ./prometheus.yml:/etc/prometheus
#   #     - ./prometheus.yml:/prometheus.yml
#   #   command:
#   #     # - "--config.file=/etc/prometheus/prometheus.yml"
#   #     - "--config.file=/prometheus.yml"

# # volumes:
# #   pgdata:
# #   prometheus:


version: '3.9'

services:
  app:
    image: prom-app:1.0
    build: 
      context: .
    ports:
      - "8001:8001"
    volumes:
      - appdata:/app
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    ports:
    - "5433:5432"    
    environment:
      POSTGRES_PASSWORD: postgres
    volumes: 
      - pgdata:/postgres
      # - ./query.sql:/docker-entrypoint-initdb.d/query.sql
      # - ./init.sh:/docker-entrypoint-initdb.d/init.sh


  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      # - ./prometheus.yml:/etc/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      # - "--config.file=/etc/prometheus/prometheus.yml"
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: docker.io/grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  appdata:
  pgdata:
  prometheus_data:
  grafana-storage: {}