global:
  scrape_interval: 1s 
  scrape_timeout: 1s  
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'fastapi'
    static_configs:
      - targets: ['app:8001']

  - job_name: "grafana"
    static_configs: 
      - targets: ["172.24.0.4:3000"]
    